### ISSUE TITLE
How can Production Manager be discovered?

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/ProductionManager#6]
What mechanisms will the Production Manager provide so that it can be found during point 3 of the user story IUNO-TDM/ProductionManagerCuraPlugin#2?

**Comment by goergch** [comment]
I could offer:
- a REST API route at the Productionmanager, at which one could make a test call
- a mdns service advertisement

Feel free to choose or make another proposal. Nothing is implemented at the moment

**Comment by bockha** [comment]
Cura seems to use [python-zeroconf](https://pypi.org/project/zeroconf/).

**Comment by goergch** [comment]
perfect. so productionmanager will advertise its service via Zeroconf/mdns/bonjour.

**Comment by bockha** [comment]
@goergch the cura plugin expects the production manager to announce itself with the type `_http._tcp.local.` name `IUNO Production Manager._http._tcp.local.`

https://github.com/IUNO-TDM/ProductionManagerCuraPlugin/blob/e4f3d669cfd90eb803514c40cbb37a47e6ee00e7/ProductionManager.py#L25

https://github.com/IUNO-TDM/ProductionManagerCuraPlugin/blob/e4f3d669cfd90eb803514c40cbb37a47e6ee00e7/ProductionManager.py#L41

**Comment by bockha** [comment]
Sservice type is expected as `_iuno-pm._tcp.local.`. Closed by https://github.com/IUNO-TDM/ProductionManagerCuraPlugin/commit/e4f3d669cfd90eb803514c40cbb37a47e6ee00e7
